
name: pom_spbu
description: POM SPBU Production App
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  blue_thermal_printer_plus: ^4.0.1
  esc_pos_utils: ^1.1.0



flutter:
  uses-material-design: true
