
name: pom_spbu
description: POM SPBU Production App
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  esc_pos_utils: ^1.1.0
  blue_thermal_printer_plus: ^2.0.6


flutter:
  uses-material-design: true
