
name: pom_spbu
description: POM SPBU Production App
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  blue_thermal_printer_plus: ^0.0.7
  esc_pos_utils: ^1.1.0




flutter:
  uses-material-design: true
